### PR TITLE
176 hotfix inf to infinity

### LINKED ISSUE #365: DerivationOutputs unable to handle infinity values
https://github.com/cambridge-cares/TheWorldAvatar/blob/98df781780dd408d033b16da878fa7e0a9c9341f/JPS_BASE_LIB/src/main/java/uk/ac/cam/cares/jps/base/derivation/DerivationOutputs.java#L187

The literal triple added via `addLiteral("http://s", "http://p", Double.POSITIVE_INFINITY)` will be serialised to `{<http://s> <http://p> Infinity.}` when updating derivation outputs in KG, resulting an invalid SPARQL update string. The valid triple should read `{<http://s> <http://p> "Infinity"^^xsd:double.}`. The same behaviour applies to negative infinity values (`Double.NEGATIVE_INFINITY`), i.e. `{<http://s> <http://p> -Infinity.}` should be corrected to `{<http://s> <http://p> "-Infinity"^^xsd:double.}`.

Potential fix:
```java
public void addLiteral(String s, String p, Number o) {
	s = trimIRI(s);
	p = trimIRI(p);
	try {
		checkIfValidIri(Arrays.asList(s, p));
	} catch (Exception e) {
		throw new JPSRuntimeException(INVALID_IRI_FOR_ADDING_LITERAL + Arrays.asList(s, p, o).toString());
	}
	if (o.equals(Double.POSITIVE_INFINITY)) {
		this.addLiteral(s, p, "Infinity", XSD.DOUBLE.toString());
	} else if (o.equals(Double.NEGATIVE_INFINITY)) {
		this.addLiteral(s, p, "-Infinity", XSD.DOUBLE.toString());
	} else {
		this.outputTriples.add(Rdf.iri(s).has(Rdf.iri(p), Rdf.literalOf(o)));
	}
}
```

### PR DESCRIPTION
**Pull request by jb2197**
This PR closes #365. Also released [`py4jps 1.0.26`](https://pypi.org/project/py4jps/1.0.26/).

### CODE REVIEW

**Review by sm453 — APPROVED** [review]

File: JPS_BASE_LIB/src/test/java/uk/ac/cam/cares/jps/base/derivation/DerivationOutputsTest.java [hunk 1]
```diff
@@ -579,9 +579,9 @@ public String formulateLiteralTripleString(String s, String p, Object o) {
 			if (o instanceof Double) {
 				if (((Double) o).isInfinite()) {
 					if (((Double) o) > 0) {
-						return "<" + s + "> <" + p + "> \"INF\"^^<" + XSD.DOUBLE.toString() + "> .";
+						return "<" + s + "> <" + p + "> \"Infinity\"^^<" + XSD.DOUBLE.toString() + "> .";
```
Comment (kokfoongcmcl) [inline JPS_BASE_LIB/src/test/java/uk/ac/cam/cares/jps/base/derivation/DerivationOutputsTest.java:582]: This is being nitpicky and I also used to do this, but in the future, please use something like String.format("<%s> <%s> \"o\"^^<%s>", s, p, o, type) to improve readability

**Review by kokfoongcmcl — APPROVED** [review]
